### PR TITLE
License code under GPL v3

### PR DESCRIPTION
**Pull request by mxve**
Previously, no explicit license was specified for contributions, so we kindly ask you to confirm your agreement to license your past contributions under GPLv3. Your confirmation helps us maintain transparency and protect the rights of both contributors and users.
@diamante0018 
@pickles976 
@FallBackITA27 

Please reply to this message confirming your approval, or feel free to reach out if you have any questions.

### CODE REVIEW

**Comment by diamante0018** [comment]
Okay. No objections from me.

**Comment by FallBackITA27** [comment]
as I stated in DMs, nothing to object.

**Comment by pickles976** [comment]
I am 100% on board, no objections. Thanks for reaching out!

**Comment by diamante0018** [comment]
All on board, merging.

**Pull request merged**
