### PR TITLE
Solve issue

### PR DESCRIPTION
**Pull request by FallBackITA27**
https://github.com/mxve/alterware-launcher/issues/114
probably could've avoided opening the issue.

### CODE REVIEW

**Comment by mxve** [comment]
Doesn't it already print (and thus log) the error when .unwrap() panics?

**Review by diamante0018 — DISMISSED** [review]
I'm not too sure about the code correctness but for the code style you should use https://en.wikipedia.org/wiki/Indentation_style#K&R

So remove the Allman braces in the panic code block

**Comment by FallBackITA27** [comment]
> Doesn't it already print (and thus log) the error when .unwrap() panics?

Nope, I modified the src just because it didn't log the error. Otherwise I wouldn't have opened the PR.

> code style
run `cargo fmt`. If you don't like the formatting and linting, you can define it in the Cargo.toml file. It's not up to me.
https://doc.rust-lang.org/rustc/lints/index.html
Not to come off as rude, I agree that the formatting you're suggesting is nicer, but it's a complaint that ultimately is up to the maintainers according to the rust book itself.

**Comment by mxve** [comment]
> > Doesn't it already print (and thus log) the error when .unwrap() panics?
> 
> Nope, I modified the src just because it didn't log the error. Otherwise I wouldn't have opened the PR.

Alright, will merge


> I'm not too sure about the code correctness but for the code style you should use https://en.wikipedia.org/wiki/Indentation_style#K&R
> 
> So remove the Allman braces in the panic code block

Looked a bit off to me too, but I just checked and ```cargo fmt``` formats it like this so it's fine.

**Comment by FallBackITA27** [comment]
> cargo fmt formats it like this

Something is wrong then, cargo fmt should format it like I submitted it and your repo has no linting defined, so I'm honestly confused as to what happened. maybe the github actions workflow y'all have passes some arguments through CLI, though that's really not recomended.

**Pull request merged**
